apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polls-redis
      project: polls
  template:
    metadata:
      labels:
        app: polls-redis
        project: polls
    spec:
      containers:
        - name: polls-redis-app
          image: redis
          ports:
            - containerPort: 6379
              name: polls-redis
---
apiVersion: v1
kind: Service
metadata:
  # name: clock-redis
  name: redis-service
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: polls-redis